Document: mingw-w64-boost
Title: Debian mingw-w64-boost Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-boost is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-boost/mingw-w64-boost.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-boost/mingw-w64-boost.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-boost/mingw-w64-boost.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-boost/html/index.html
Files: /usr/share/doc/mingw-w64-boost/html/*.html
